### DISCUSSION TITLE
nuget push   github    error 400

### DISCUSSION THREAD

**Discussion by bbhxwl** [NuGet/Home#11301] [Q&A]
Run nuget push   */bin/Release/*.nupkg *** -Source github -SkipDuplicate 
Pushing AdlCommon.1.0.0.nupkg to 'https://nuget.pkg.github.com/bbhxwl'...
  PUT https://nuget.pkg.github.com/bbhxwl/
WARNING: No destination repository detected. Ensure the source project has a 'RepositoryUrl' property defined. If you're using a nuspec file, ensure that it has a repository element with the required 'type' and 'url' attributes.
  BadRequest https://nuget.pkg.github.com/bbhxwl/ 35ms
Response status code does not indicate success: 400 (Bad Request).
Error: Process completed with exit code 1.

```
name: .NET Core

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 建立.netcore环境
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: 安装依赖
      run: dotnet restore
    - name: 构建
      run: dotnet build --configuration Release --no-restore
    - name: 添加github仓库
      run: |
        nuget sources add -name github -Source https://nuget.pkg.github.com/bbhxwl/index.json -Username bbhxwl -Password ${{ secrets.TOKEN }}
    - name: 安装nuget 
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'
    - name: Create the package
      run: dotnet pack --configuration Release AdlCommon
    - name: 发布生成包到github和nuget
      run: |
        nuget push   */bin/Release/*.nupkg ${{ secrets.TOKEN }} -Source github -SkipDuplicate 

```

**Comment by erdembayar** [comment]
Hi.
By looking at examples from [doc](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push) nuget push use actual source url instead of source name `github`. Please try with actual source url `https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push` and let me know if works for you.  `nuget push   */bin/Release/*.nupkg ${{ secrets.TOKEN }} -Source https://nuget.pkg.github.com/bbhxwl/index.json  -SkipDuplicate `

**Reply by LITTOMA** [reply]
doesn't works for me.

**Reply by erdembayar** [reply]
@LITTOMA 
Please include actual error message and your script for your issue context. There could be different errors depending on situation.

**Comment by LITTOMA** [comment]
@erdembayar 
workflow:
``` yaml
name: Publish Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
      
      - name: Add github packages source
        run: dotnet nuget add source --username LITTOMA --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LITTOMA/index.json"
    
      - uses: actions/checkout@v3

      - name: Restore packages
        run: dotnet restore
      
      - name: Build and publish the package
        run: |
          cd PaletteQuantizer
          dotnet pack --configuration Release
          dotnet nuget push "bin/Release/PaletteQuantizer.1.0.0.nupkg"  --api-key ${{ secrets.PAT }} --source "https://nuget.pkg.github.com/LITTOMA/index.json"

        
```

outputs:
```
PaletteQuantizer -> D:\a\PaletteQuantizer\PaletteQuantizer\PaletteQuantizer\bin\Release\netstandard2.1\PaletteQuantizer.dll
  Successfully created package 'D:\a\PaletteQuantizer\PaletteQuantizer\PaletteQuantizer\bin\Release\PaletteQuantizer.1.0.0.nupkg'.
Pushing PaletteQuantizer.1.0.0.nupkg to 'https://nuget.pkg.github.com/LITTOMA'...
  PUT https://nuget.pkg.github.com/LITTOMA/
warn : No destination repository detected. Ensure the source project has a 'RepositoryUrl' property defined. If you're using a nuspec file, ensure that it has a repository element with the required 'type' and 'url' attributes.
  BadRequest https://nuget.pkg.github.com/LITTOMA/ 320ms
error: Response status code does not indicate success: 400 (Bad Request).
```

**Reply by erdembayar** [reply]
Please add this line as mine in your cspoj file it'll solve above issue:
https://github.com/erdembayar/JustLargePackage/blob/6abe1221052c554d891d293b69df29af049d4f56/JustLargePackage/JustLargePackage.csproj#L8

**Reply by erdembayar** [reply]
Here my `dotnet nuget push` work https://github.com/erdembayar/JustLargePackage/blob/main/.github/workflows/dotnet.yml

**Comment by LITTOMA** [comment]
OK, I found a workaround [here](https://github.com/NuGet/Home/issues/8580#issuecomment-555696372).

Updated my script and it works now:
``` yaml
name: Publish Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0

      - uses: actions/checkout@v3

      - name: Restore packages
        run: dotnet restore
      
      - name: Build
        run: |
          cd PaletteQuantizer
          dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
      
      - name: Publish
        run: |
          for f in ./PaletteQuantizer/bin/Release/*.nupkg
          do
            curl -vX PUT -u "LITTOMA:${{ secrets.PAT }}" -F package=@$f https://nuget.pkg.github.com/LITTOMA/
          done
        shell: bash
```
