### ISSUE TITLE
Reliability issues while publishing packages to GPR, using GitHub Actions

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#10045]
This is a new issue forked from the closed issue: `dotnet nuget push to GPR -- Invalid or unrecognized response` #8580

Pasting some of the responses from that issue:

---

@JB101UK commented:
I've been attempting to upload dotnet nupkgs to GitHub packages. I've followed all of the troubleshooting advice, I've got my tokens, my repository url set, my nuget.config file configured, but I find that both pushing/pulling packages is relatively intermittent. Sometimes it just works - other times I get the following error:

Pushing <packageName> to "http://nuget.pkg.github.com/<Owner> PUT https://nuget.pkg.github.com/<Owner>/ An error encountered when fetching PUT http://nuget.pkg.github.com/<Owner>. The request will now be retried. An error occurred while sending the request. The response ended prematurely. PUT https://nuget.pkg.github.com/<Owner> An error encountered when fetching PUT http://nuget.pkg.github.com/<Owner>. The request will now be retried. An error occurred while sending the request. The response ended prematurely. PUT https://nuget.pkg.github.com/<Owner> error: An error occurred while sending the request. error: The response ended prematurely.

It's frustrating because sometimes it just works.
Package is pushed.

And other times I can keep re-submitting the same request and it will fail for a while, and eventually just push, without any changes/modification to my code/dotnet nuget push statement.

I see there's been a lot of discussion about this on the forums. I'm presuming it's just a temperamental fault that will be rectified?

Thanks

---

@bjorhn commented 

'm having the exact same problem as @JB101UK. I have two private repos set up, they're both designed to build and push packages to GitHub and they're set up with near-identical scripts. In one of the repos the push succeeds 100% of the time, and in the other repo it only succeeds about 20-25% of the time. All I have to do in order to make it work is run the same action over and over until it goes through. **I don't even have to create a new PR, I just keep clicking on the failed workflow -> "Re-run jobs" until it works**.

My failing action looks like this:
```
name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/bjorhn/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore Nuget packages
        run: dotnet restore
      - name: Create the nuget package
        run: dotnet pack MyProject.csproj --configuration Release --no-build --output bin/Release/Publish
      - name: Publish to GitHub
        run: dotnet nuget push bin/Release/Publish/**/*.nupkg --skip-duplicate
```
The only difference between the working and the failing repo/action is that the working one performs a dotnet build instead of a dotnet restore, and doesn't set the --no-build flag when calling dotnet pack.

---

@bgilbert6 commented 

No matter what I try I only ever get this reply:
`
warn : No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/ORG'. To save an API Key for a source use the 'setApiKey' command.
info : Pushing pkg.0.0.5.nupkg to 'https://nuget.pkg.github.com/ORG'...
info :   PUT https://nuget.pkg.github.com/ORG/
info :   NotFound https://nuget.pkg.github.com/ORG/ 519ms
error: Response status code does not indicate success: 404 (Not Found).
`

I can manually go to the nuget.pkg.github.com url and there is definitely something there. But the PUT request 404s

---

@RehanSaeed commented

Also been through a few iterations and approaches to this.  Sometimes the following works, other times I get errors:

```yml
    - name: Publish to github
      run: dotnet nuget push **/*.nupkg -s https://nuget.pkg.github.com/[USERNAME]/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols true
      working-directory: src
```

[intermittent] errors with: An error was encountered when fetching 'PUT https://nuget.pkg.github.com/daltskin/'. The request will now be retried. An error occurred while sending the request.

Now, I'm just using curl to push the package and it seems more reliable :)  

Replace `[PACKAGE]` with your package name
Replace `[USERNAME]` with your username

Github workflow extract:

```yml

    - name: Package
      run: dotnet pack --configuration Release --no-build -p:PackageVersion=${{ env.GitVersion_SemVer}}
    
    - name: Publish to github (using curl)
      run: curl -vX PUT -u "[USERNAME]:${{ secrets.GITHUB_TOKEN }}" -F package=@[PACKAGE].${{ env.GitVersion_SemVer}}.nupkg https://nuget.pkg.github.com/[USERNAME]/
      working-directory: src/bin/Release
```

---

@rido-min commented

I got it working with `dotnet nuget push` [here](https://github.com/ridomin/DeviceClientFactory/blob/master/.github/workflows/dotnetcore.yml#L33)
.. but didnt work when using a repo under a GitHub organization, so I switched to curl

---

@Fronix commented

I'm using my nuget action under an organization and this is what's been working for us after many trial and errors.
```yaml
      - name: Publish backend nuget
        run: curl -vX PUT -u "user:${{ secrets.package_secret }}" -F package=@Publish/backend.${{env.VERSION}}.nupkg https://nuget.pkg.github.com/myorg/
        shell: bash
        working-directory: ${{env.backend-directory}}
      - name: Publish frontend nuget
        run: curl -vX PUT -u "user:${{ secrets.package_secret }}" -F package=@Publish/backend.${{env.VERSION}}.nupkg https://nuget.pkg.github.com/myorg/
        shell: bash
        working-directory: ${{env.frontend-directory}}
```

---

@Airn5475 commented

I know this issue is closed, but I continue to see issues with the methods mentioned above. One time it works and then another time it doesn't. I am also working under and organization. This is SO Frustrating!

**Comment by erdembayar** [comment]
@anangaur 
Do you know contact to GPR team? I need to ask questions.

**Comment by erdembayar** [comment]
@anangaur 
I want ask if Github Package Repository team have logging and metrics for failure/fault.

**Comment by nadesu** [comment]
Hey, my team supports GitHub Packages for Nuget registry. We just received a lead to this thread. Pls let us know how we can help

**Comment by NamrataJha** [comment]
Hey @anangaur @erdembayar I tried but I am unable to repro this. I tried publishing via both `dotnet restore` and `dotnet build` continuously for 4-5 hours in a workflow but didn't run into any failures.
Can you confirm if this issue is still relevant?

**Comment by erdembayar** [comment]
> dotnet nuget push

Thank you for testing this for us. 
Did you run `dotnet nuget push ` after each iteration of `dotnet restore` and `dotnet build`?
Could you be able to share your script here? I want to verify if's testing scenario we're interested in.
Also, one customer mentioned it doesn't work under Github organization repo. Did you test scenario too?

**Comment by NamrataJha** [comment]
I used the following workflows -

dotnet build
```
name: dotent-restore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/namratajha/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build Nuget packages
        run: dotnet build -p:PackageVersion=1.0.0-${{ github.sha }}
        env:
          sha: ${{ github.sha }}
      - name: Create the nuget package
        run: dotnet pack AppLogger.csproj -p:PackageVersion=1.0.0-${{ github.sha }} --configuration Release --output bin/Release/Publish
        env:
          sha: ${{ github.sha }}
      - name: Publish to GitHub
        run: dotnet nuget push bin/Release/Publish/**/*.nupkg --skip-duplicate
        env:
          sha: ${{ github.sha }}
```

dotnet restore
```
name: dotent-restore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/namratajha/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore Nuget packages
        run: dotnet restore -p:PackageVersion=1.0.0-${{ github.sha }}
        env:
          sha: ${{ github.sha }}
      - name: Create the nuget package
        run: dotnet pack nuget-test.csproj -p:PackageVersion=1.0.0-${{ github.sha }} --configuration Release --no-build --output bin/Release/Publish
        env:
          sha: ${{ github.sha }}
      - name: Publish to GitHub
        run: dotnet nuget push bin/Release/Publish/**/*.nupkg --skip-duplicate
        env:
          sha: ${{ github.sha }}
```

Haven't checked under Github organization repo. Will test this scenario as well.
