### ISSUE TITLE
Generating MSBuild Binary log from nuget restore command

### ISSUE THREAD

**Issue by vatsan-madhavan** [NuGet/Home#10135]
How can I generate MSBuild Binary log from nuget client commands like restore ? 

`nuget restore` resolves into something like `msbuild.exe "%temp%\NuGetScratch\ro0d0kct.z0t.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="%temp%\NuGetScratch\w3s4ivaf.f43.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="<path to nuget.exe>" /p:RestoreSolutionDirectory="<path to sln directory>" /p:SolutionDir="<path to solution dir>" /p:SolutionNam=<solution name>`

How can I get it to pass `/bl` to msbuild so that a binary log is output at the end of nuget restore?

**Comment by nkolev92** [comment]
Hey @vatsan-madhavan, 
NuGet.exe restore just uses MSBuild to read the projects, the restore is actually run in the NuGet.exe process. 

Either way, yo get a binlog from that msbuild part, you can use an env var: 

See details here: https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-environment-variables: 

`NUGET_RESTORE_MSBUILD_ARGS` is the thing you are looking for.

**Comment by vatsan-madhavan** [comment]
Thanks! 

Can NuGet itself generate its own logs that are compatible with msbuild binary log format? Or is that not possible?

**Comment by zivkan** [comment]
@vatsan-madhavan if you use msbuild restore instead of nuget.exe restore, `msbuild -t:restore -bl`, that's another way to you can get a binlog. In fact, if you don't have any projects packages.config, I'd highly recommend this instead of nuget.exe.

However, just like nuget.exe restore, the msbuild execution is just to collect project information. All the restore logic (calculating dependency graph, selecting packages, downloading packages) happens inside a single `RestoreTask`, so the binlog isn't very interesting.

What kind of information are you hoping to find in the binlog?

**Comment by vatsan-madhavan** [comment]
Thanks, I just want to consolidate/compress logs- binary logs are small and more efficient. Looks like it's not possible.

**Comment by abatishchev** [comment]
Here's what worked for me using a YAML task in ADO:

```yaml
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    restoreArguments: '/binarylogger:LogFile=$(Agent.TempDirectory)\msbuild.binlog'
    projects: '$(RepoRoot)\src\Service\Host.proj'
    feedsToUse: config
    nugetConfigPath: '$(RepoRoot)\NuGet.config'
```

And then immediately thereafter:

```yaml
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Agent.TempDirectory)\msbuild.binlog'
    artifactName: 'binlogs'
  condition: always()
```

Since it's likely for troubleshooting a failure, it must have `condition: always()`.
