### ISSUE TITLE
NuGet pack task intermittently succeeds, but no output is generated 

### ISSUE THREAD

**Issue by asklar** [NuGet/Home#10959]
I'm seeing some cases where we call the nuget ADO task to pack some stuff, it succeeds, but it doesn't do anything. Then the next step in my pipeline which needs to use the nupkg, fails because it can't find it

Any idea what might be happening? there are no logs collected even though verbosityPack=detailed

![image](https://user-images.githubusercontent.com/22989529/122891275-3f8fa400-d2f9-11eb-83af-2660b6807ccd.png)

[Pipelines Run](https://dev.azure.com/ms/react-native-windows/_build/results?buildId=182915&view=logs&j=a6f06978-9299-5b6a-c269-a1a1b0de305a&t=3c4dd10c-0c20-53f7-9147-0a20eda58dd9)

YAML:
```yaml
  # NuGetCommand@2 workaround: https://developercommunity.visualstudio.com/content/problem/288534/vsts-yaml-build-failure-the-task-name-nugetcommand.html
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
    displayName: '${{ parameters.packageId }} - Nuget pack'
    inputs:
      command: pack
      verbosityPack: 'Detailed'
      packagesToPack: $(System.DefaultWorkingDirectory)/ReactWindows/${{ parameters.packageId }}.nuspec
      packDestination: $(System.DefaultWorkingDirectory)/NugetRootFinal
      buildProperties: version=${{ parameters.packageVersion }};id=${{ parameters.packageId }};${{ parameters.buildProperties }}
```
