### ISSUE TITLE
Issue with Package source mapping by adding prefix feed. When executing dotnet restore facing issue, where it is inputting 5times feed as prefix

### ISSUE THREAD

**Issue by crsreddy1447** [NuGet/Home#12328]
Issue with Package source mapping by adding prefix feed. When executing dotnet restore facing issue, where it is inputting 5times feed as prefix
`error NU1100: Unable to resolve 'Intergraph.TestTools.Clipper.UnitTesting (>= 1.0.8)' for 'net6.0'. PackageSourceMapping is enabled, the following source(s) were not considered: feed-feed-hexagonppmclipper, feed-feed-hexagonppmclipperfeaturebranch, feed-feed-SDXInternal, nuget.org, PPM. [/agent/_work/1/s/SPF/Services/xxxxxxxxxxxxxxxxxxx.netcore.csproj`

`Common.netstandard (>= 1.0.37)' for 'net6.0'. PackageSourceMapping is enabled, the following source(s) were not considered: feed-feed-feed-feed-feed-hxxxxxxxper, feed-feed-feed-feed-feed-hxxxxxrfeaturebranch, feed-feed-feed-feed-feed-SxxInternal, nuget.org, PPM.`

these kind of error I am facing. I am using Dotnet restore in Linux Azure virtual machine scale set pool as agent machine.

```
          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            retryCountOnTaskFailure: 3
            inputs:
              command: restore
              projects: "$(assemblyPath)"
              feedsToUse: config
              nugetConfigPath: NuGet.Config
```
Declared feeds in this way as per this link https://github.com/NuGet/Home/issues/11406
```
		<packageSource key="feed-PPM">
			<package pattern="webapi.nuget" />
		</packageSource>
		<packageSource key="PPM">
			<package pattern="webapi.nuget" />
		</packageSource>
```

Please help me how to resolve this issue
