### ISSUE TITLE
Publishing to BAR/Maestro will no longer support tokens

### ISSUE THREAD

**Issue by premun** [NuGet/Home#13656]
I noticed that you're still using `$(MaestroAccessToken)` when publishing internal builds in https://github.com/NuGet/NuGet.Client/blob/46f80a3f1a83f3c5f33a20fa9fb72871e1e2d4eb/build/publish.proj#L71.

This token is getting deprecated in favour of using a secretless auth via a service connection.
You will need to change how you do this or your internal builds will soon break.
The change is not complicated and goes as follows:

If your pipeline has something like this:
```yaml
- task: CmdLine@2
  displayName: "Publish to the .NET Core build asset registry (BAR)"
  inputs:
    script: dotnet msbuild $(Build.Repository.LocalPath)\build\publish.proj /t:PublishToBuildAssetRegistry /property:NuGetClientNupkgsDirectoryPath=$(Build.Repository.LocalPath)\artifacts\$(NupkgOutputDir) /property:BUILD_BUILDNUMBER=$(Build.BuildNumber) /property:BUILD_SOURCEBRANCH=$(Build.SourceBranchName) /property:BUILD_SOURCEVERSION=$(Build.SourceVersion) /property:BUILD_REPOSITORY_URI=$(Build.Repository.Uri) /property:BUILD_REPOSITORY_NAME=$(Build.Repository.Name) /property:ArtifactsLogDir=$(Build.Repository.LocalPath)\artifacts\manifests\ /property:MaestroApiEndpoint=$(MaestroApiEndpoint) /property:MaestroAccessToken=$(MaestroAccessToken) /binarylogger:$(Build.StagingDirectory)\binlog\21.PublishToBuildAssetRegistry.binlog
    workingDirectory: cli
    failOnStderr: true
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_MULTILEVEL_LOOKUP: true
  condition: "and(succeeded(),eq(variables['PublishArtifactsToDotNetBuildAssetRegistry'], 'true'), eq(variables['BuildRTM'], 'false'))"
```

it will need to change to something like this:

```yaml
- task: AzureCLI@2
  displayName: "Publish to the .NET Core build asset registry (BAR)"
  inputs:
    azureSubscription: "Darc: Maestro Production"
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      dotnet msbuild $(Build.Repository.LocalPath)\build\publish.proj /t:PublishToBuildAssetRegistry /property:NuGetClientNupkgsDirectoryPath=$(Build.Repository.LocalPath)\artifacts\$(NupkgOutputDir) /property:BUILD_BUILDNUMBER=$(Build.BuildNumber) /property:BUILD_SOURCEBRANCH=$(Build.SourceBranchName) /property:BUILD_SOURCEVERSION=$(Build.SourceVersion) /property:BUILD_REPOSITORY_URI=$(Build.Repository.Uri) /property:BUILD_REPOSITORY_NAME=$(Build.Repository.Name) /property:ArtifactsLogDir=$(Build.Repository.LocalPath)\artifacts\manifests\ /binarylogger:$(Build.StagingDirectory)\binlog\21.PublishToBuildAssetRegistry.binlog
    workingDirectory: cli
    failOnStderr: true
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_MULTILEVEL_LOOKUP: true
  condition: "and(succeeded(),eq(variables['PublishArtifactsToDotNetBuildAssetRegistry'], 'true'), eq(variables['BuildRTM'], 'false'))"
```

The differences between the snippets above are:
-	AzureCLI@2 task is used
-	The “Darc: Maestro Production” service connection is used.
Your pipeline will need to be approved to use this connection (reach out to First Responders).
-	The $(MaestroAccessToken) secret is removed
