### ISSUE TITLE
Migrating to .NET CLI on Ubuntu with a nuspec

### ISSUE THREAD

**Issue by jochenjonc** [NuGet/Home#14181]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

After reading the release notes of Azure DevOps I stumbled upon the following: [Pipelines using Ubuntu 24.04 will show warnings for certain tasks](https://learn.microsoft.com/en-us/azure/devops/release-notes/2025/sprint-252-update#pipelines-using-ubuntu-2404-will-show-warnings-for-certain-tasks).

I tried to change the following the NuGetCommand@2 to a DotNetCoreCLI@2, but in some cases I create a NuGet without a csproj file, only a nuspec file and dotnet pack doesn't support that.

I also found this open issue regarding this missing feature: https://github.com/NuGet/Home/issues/4254

Are there plans to add this?

### Additional Context and Details

Example of a NuGetCommand@2 that uses a nuspec file and is not a csproj:

```yaml
    - task: NuGetCommand@2
      displayName: 'Packaging NuGet'
      inputs:
        command: 'pack'  
        packagesToPack: '**/example.nuspec'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'gitVersion_FullSemVer'   
        packDestination: '$(Build.ArtifactStagingDirectory)/Nuget Packages'
```

Converted DotNetCoreCLI@2 that doesn't work:

```yaml
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        packagesToPack: '**/example.nuspec'
        packDirectory: '$(Build.ArtifactStagingDirectory)/Nuget Packages'
        versioningScheme: byEnvVar
        versionEnvVar: 'gitVersion_FullSemVer'
```
