### ISSUE TITLE
nuget source password encryption story

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1851]
Rob adding text on 2/10/2017:
nuget.exe | dotnet.exe can now use encrypted passwords in nuget.config files -- when running on windows ONLY.
Ideally, we'd support dotnet.exe on other platforms too, so they don't need to store passwords via cleartext.

This would need APIs from .NET Core. See the related https://github.com/dotnet/corefx/issues/6746

**Comment by yishaigalatzer** [comment]
CC @anurse @davidfowl

**Comment by emgarten** [comment]
Is this needed for xplat?

**Comment by yishaigalatzer** [comment]
Yes but not for rc, and debatable for rtm

**Comment by yishaigalatzer** [comment]
@emgarten when RC is out the door, please start a thread with Stephen Toub

**Comment by mountgellert** [comment]
Hi @rrelyea , is there any update on this or on https://github.com/dotnet/corefx/issues/6746 ?

**Comment by mountgellert** [comment]
@mrward , How does your change fix this? Still cannot seem to see a way to use encrypted credentials from a Linux machine.

**Comment by mrward** [comment]
@mountgellert - For some reason merging the latest code into my fork closed this issue when it should not have. Re-opening.

**Comment by psmulovics** [comment]
Any news on this item?

**Comment by guidobouman** [comment]
What's the roadmap on this? Is the NuGet or the dotnet project responsible for this implementation? I can't seem to find anything about this in https://github.com/dotnet/designs/issues/11

**Comment by psmulovics** [comment]
any news on this item?

**Comment by ghost** [comment]
Bump for update.

**Comment by koliyo** [comment]
Please make this a priority, if Microsoft is serious about true cross-platform .NET application development.

We need both MacOS and Linux support!

**Comment by dquist** [comment]
Another serious shortcoming here is that, even on Windows, there's no way to securely enter the password. It can only be provided as plain text through the `-Password` option, in which case it will likely be logged to the shell history.

Come on, this is like CLI authentication 101. There needs to be a way to enter secrets interactively.

See https://github.com/NuGet/Home/issues/8131

**Comment by Swoorup** [comment]
* Upgrades everything to use dotnet core instead of mono. 
* Everything works fine locally. 
* Hopes on to build machine, which repulls packages.
* Notices this damn bug. 
* Cleans packages locally, notices this damn bug.

**Comment by MaxHorstmann** [comment]
> Please make this a priority, if Microsoft is serious about true cross-platform .NET application development.

> We need both MacOS and Linux support!

Friendly +1. We're evaluating GitHub Actions / Packages for our build pipeline. A bit simplified, here's the workflow we have in mind:

```
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Add package source
      run:  dotnet nuget add source https://nuget.pkg.github.com/ourteam/index.json -n GPR --store-password-in-clear-text -u SomeUser -p ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
```

So basically, the GitHub Packages NuGet source is injected at build time [using the GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token). With the entire build running on a Linux image, we're forced to use `--store-password-in-clear-text` - otherwise, the "Add package source" step fails with the "Encryption is not supported on non-Windows platforms" error.

While GH Actions thankfully doesn't log the cleartext token (shows up as `-p ***`), it's worrying that it is stored somewhere inside an ephemeral build container (in `nuget.config` or elsewhere) for a certain period of time. In particular given the [wide range of permissions for the GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token). Supporting password encryption on non-Windows platforms would alleviate that concern.
