### ISSUE TITLE
"Access is Denied" Using Spinnaker/Packer When Adding a Source

### ISSUE THREAD

**Issue by mellena1** [NuGet/Home#5357]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.1.0.2450

OS version (i.e. win10 v1607 (14393.321)): Windows 2012 R2

Worked before? If so, with which NuGet version: Nope, I'm new to NuGet.

## Detailed repro steps so we can see the same problem

1. Spinnaker uses Packer to build an AMI to use with Amazon Web Services. During this build, I am using a Powershell script to install NuGet.CommandLine using Chocolatey, add an Artifactory Repo (using nuget sources add ...), and then install a package. 

2. The same commands work if I run them manually from within the instance using RDP, but when using Packer the Powershell spits out "Access is Denied." when trying to add the source. That is the only error I receive. I know the Packer and Spinnaker stuff isn't really your expertise, but I was wondering if there is a file permissions issue that you could at least send me in the right direction with.

3. Just extra info: Packer runs the Powershell as an Admin.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
```
    amazon-ebs: NuGet Version: 4.1.0.2450
    amazon-ebs: System.Security.Cryptography.CryptographicException: Access is denied.
    amazon-ebs:
    amazon-ebs: at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
    amazon-ebs: at NuGet.Configuration.EncryptionUtility.EncryptString(String value)
    amazon-ebs: at NuGet.Configuration.PackageSourceCredential.FromUserInput(String source, String username, String password, Boolean storePasswordInClearText)
    amazon-ebs: at NuGet.CommandLine.SourcesCommand.AddNewSource()
    amazon-ebs: at NuGet.CommandLine.Command.ExecuteCommandAsync()
    amazon-ebs: at NuGet.CommandLine.Command.Execute()
    amazon-ebs: at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```
