### ISSUE TITLE
VSTS nuget task. Unable to set 'externalFeedCredentials' for multiple feeds

### ISSUE THREAD

**Issue by Rora** [NuGet/Home#6974]
## Details about Problem

NuGet product used: VSTS build task 'NuGet' (YML build)
NuGet version: 4.4.1

**Nuget task configuration**
```
- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    feedsToUse: config
    nugetConfigPath: 'NuGet.config'
    externalFeedCredentials: *tried all sorts of values here...*
    noCache: true
```

### Issue
When creating a (normal) VSTS build and adding a nuget task, with the restore command selected, we get an option ```Credentials for feeds outside this account/collection``` which allows us to set multiple feed credentials. 

When using the same task in a YML VSTS build, the corresponding property ```externalFeedCredentials``` only accepts 1 feed credential.

### Expected behavior
externalFeedCredentials should be an array, if externalFeedCredentials already accepts a serialized array as a string it should be documented so.

## Detailed repro steps so we can see the same problem

1. Create a YML build in vsts
1. Add the nuget task as configured above
1. Notice that you can only define 1 externalFeedCredential and not multiple
