### ISSUE TITLE
 NuGet.Protocol.Plugins.ProtocolException: The message type 'Cancel' is invalid at this time. When using azure pipelines and version 4.8.1

### ISSUE THREAD

**Issue by waterfoul** [NuGet/Home#7489]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx):  4.8.1.5435 / 4.8.1-rtm.5435+6007570d889b9392fb9826a6d31f99f6acf9e440

OS version (i.e. win10 v1607 (14393.321)): Microsoft Windows Server 2016 Standard 10.0.14393 Build 14393

Worked before? If so, with which NuGet version: 4.7.1

## Detailed repro steps so we can see the same problem
1. Setup a build pipeline in azure dev ops with the machine in question
2. Setup a private nuget repo
3. Check a project into a git repo using that nuget repo via nuget.config
4. Setup a build pipeline using with the following yml template and the git repo from #3
```yml
parameters:
  solution: ''

steps:
  # Nuget
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '4.7.X'
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      feedsToUse: 'config'
      arguments: ${{ format('restore "{0}" -DirectDownload -NoCache', parameters.solution) }}
```
5. Start the build

You will receive errors similar to that which is reported [here](https://developercommunity.visualstudio.com/content/problem/376924/nuget-restore-failing-nuget-command-task-version-2.html)
