### ISSUE TITLE
Not able to push packages to DevOps artifacts using Dotnet Nuget Push

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7792]
_From @mdmoura on February 13, 2019 18:29_

## Steps to reproduce

I tried to push a package to Azure Devops Artifacts, after creating a feed, in two ways:

    dotnet nuget push 
       --source https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v3/index.json 
       MyPackage.nupkg

    dotnet nuget push 
       --source https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2
       --api-key MyPAT 
       MyPackage.nupkg

I created the PAT as follows:
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops

Just it case I gave it full access ...

## Expected behavior

I would expect the package to be pushed to the feed.

## Actual behavior

When using version 3 I got the following error:

     error: Unable to load the service index for source 
                https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v3/index.json 
     error: Response status code does not indicate success: 401 (Unauthorized).

When using version 2 I got the following error:

    info : Pushing MyPackage.nupkg to 
             'https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2'...
    info :   PUT https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2
    info :   Unauthorized https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2 563ms
    error: Response status code does not indicate success: 401 (Unauthorized).

Using the browser I can access both version 2 and 3 urls (for version 3 I needed to sign in on Azure)

## Environment data

.NET Core SDK (reflecting any global.json):
Version:   2.2.104
Commit:    73f036d4ac

Runtime Environment:
OS Name:     Mac OS X
OS Version:  10.14
OS Platform: Darwin
RID:         osx.10.14-x64
Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
Version: 2.2.2
Commit:  a4fd7b2c84

.NET Core SDKs installed:
2.2.104 [/usr/local/share/dotnet/sdk]

_Copied from original issue: dotnet/cli#10778_

**Comment by rrelyea** [comment]
Relevant docs are here: https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops
Not sure if the new credential provider would also help: https://github.com/Microsoft/artifacts-credprovider

@alexmullans

**Comment by mdmoura** [comment]
@rrelyea I followed again (I did that before) the steps you mentioned and some extra work.

I leave the steps because it might be useful for someone else (This is for MAC and Azure DevOps):

1 - Follow steps in here:
     https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops

2 - Install new credential provider:
      https://github.com/Microsoft/artifacts-credprovider

3 - Generate PAT as in here:
      https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops

4 - Add the following nuget.config value on same path where nuget.exe or script that using nuget.exe or dotnet nuget:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="MyFeed" value="https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <MyFeed>
      <add key="Username" value="UsernameInDevops - I think it is always an email address" />
      <add key="ClearTextPassword" value="PAT Obtained in Step 3" />
    </MyFeed>
  </packageSourceCredentials>
</configuration>
```

Use ClearTextPassword in  Nuget.config instead of Password because encrypted password is not supported ...

5 - Finally run the command:

    dotnet nuget push MyPackage.nupkg --source MyFeed --api-key key


**Question that remains**

Isn't there a way to not use Nuget.config and include everything in dotnet push, e.g.:

    dotnet nuget push 
      MyPackage.nupkg 
      --source https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v3/index.json 
      --api-key MyPat

When trying this I wasn't able to make it work as I stumbled in a problem:
https://github.com/NuGet/Home/issues/7519

But again I would not want to sign in manually ...

I suppose it would be necessary to pass Username and Password but I do not see those options in donet nuget push command ...

**Comment by rrelyea** [comment]
@alexmullans should be able to review and advise. you should not need clear text password, i believe.

**Comment by infin8x** [comment]
@rrelyea that's right. With the right version of `dotnet` (2.1.400 or greater, though latest is always preferable), as long as you've installed the cred provider using the [readme instructions](https://github.com/Microsoft/artifacts-credprovider/), which it sounds like you have, push should show a device flow prompt in the logs when you run the `dotnet nuget push` command with only the `--source` and `--api-key`.

**Comment by Lutando** [comment]
Any movement on this?

**Comment by RogerioDosSantos** [comment]
Indeed following the steps described by @rrelyea using the microsoft/dotnet:2.2-sdk docker image, I can confirm that we still get Response status code does not indicate success: 401 (Unauthorized).

**Comment by buck-mbeer** [comment]
I ran into an issue with `dotnet nuget push`ing to an Azure Artifacts feed in Azure Devops Server 2019 that turned out to be a bug in the 2.1 .NET Core CLI which has been fixed in 3.0 preview builds. I was able to resolve by splitting my Azure Pipeline into a Build Job which runs in the .NET Core 2.1 SDK container and a Push job which runs in the 3.0 SDK container. If it's of use to any of you, my (rather hefty) pipeline is shared below:

```
###########################################################
### Change these values when copying this pipeline      ###
### Pipeline additionally requires these variables-     ###
###   $(My.Endpoint)                                    ###
###   $(My.GuidEndpoint)                                ###
###   $(My.User)                                        ###
###   $(My.PAT)                                         ###
###########################################################
variables:
  BuildConfiguration: Release
  Project.File.Path: MyLibrary.csproj
  Project.Assembly.Name: MyLibrary
  Project.Version: '1.0.0'
###########################################################
name: $(Project.Version)-$(Date:yyyyMMdd)$(Rev:rr)
resources:
  containers:
  - container: NetCoreSDK21
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    # We must manually map the agent work folder until a resolution for this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/11137 flows into Azure Devops Server
    options: -v /home/azpagent/agent/_work:/__w/
  - container: NetCoreSdk30
    image: mcr.microsoft.com/dotnet/core/sdk:3.0
trigger:
  batch: true
  branches:
    include:
    - develop
    - release/*
  paths:
    exclude:
    - ReadMe.md
jobs:
- job: Build
  container: NetCoreSDK21
  steps:
  - script: |
      echo "##vso[task.setvariable variable=NuGet.CredentialProvider.SessionTokenCache.Enabled]true"
      echo "##vso[task.setvariable variable=Dotnet.System.Net.Http.UseSocketsHttpHandler]0"
      echo "##vso[task.setvariable variable=NuGet.Authentication.Types]basic"
    displayName: Set container environment variables
  - script: |
      ENDPOINTSTRING="{\"endpointCredentials\": [{\"endpoint\":\"$(My.Endpoint))\", \"username\":\"$(My.User)\", \"password\":\"${MAPPED_SECRET}\"},{\"endpoint\":\"$(My.GuidEndpoint)\", \"username\":\"$(My.User)\", \"password\":\"${MAPPED_SECRET}\"}]}"
      echo "##vso[task.setvariable variable=Vss.NuGet.External.Feed.EndPoints]${ENDPOINTSTRING}"
    displayName: Set NuGet feed credentials
    env:
      MAPPED_SECRET: $(My.PAT)
  - script: wget -O - https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | bash
    displayName: 'Install artifacts credential provider'
  - script: dotnet restore $(Project.File.Path) -s "$(My.GuidEndpoint)" -s "https://api.nuget.org/v3/index.json"
    displayName: 'Dotnet restore'
  - task: DotNetCoreCLI@2
    displayName: 'Dotnet build'
    inputs:
      projects: '$(Project.File.Path)'
      arguments: '-c $(BuildConfiguration) --no-restore'
  - task: DotNetCoreCLI@2
    displayName: 'Dotnet pack'
    inputs:
      command: pack
      nobuild: true
      includesymbols: true
      versioningScheme: byEnvVar
      versionEnvVar: 'BUILD_BUILDNUMBER'
      verbosityPack: Normal
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: NuGetPackage'
    inputs:
      ArtifactName: NuGetPackage
- job: Push
  dependsOn: Build
  container: NetCoreSdk30
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: NuGetPackage
  - script: |
      echo "##vso[task.setvariable variable=NuGet.CredentialProvider.SessionTokenCache.Enabled]true"
      echo "##vso[task.setvariable variable=Dotnet.System.Net.Http.UseSocketsHttpHandler]0"
      echo "##vso[task.setvariable variable=NuGet.Authentication.Types]basic"
    displayName: Set container environment variables
  - script: |
      ENDPOINTSTRING="{\"endpointCredentials\": [{\"endpoint\":\"$(My.Endpoint))\", \"username\":\"$(My.User)\", \"password\":\"${MAPPED_SECRET}\"},{\"endpoint\":\"$(My.GuidEndpoint)\", \"username\":\"$(My.User)\", \"password\":\"${MAPPED_SECRET}\"}]}"
      echo "##vso[task.setvariable variable=Vss.NuGet.External.Feed.EndPoints]${ENDPOINTSTRING}"
    displayName: Set NuGet feed credentials
    env:
      MAPPED_SECRET: $(My.PAT)
  - script: wget -O - https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | bash
    displayName: 'Install artifacts credential provider'
  - script: dotnet nuget push $(Build.ArtifactStagingDirectory)/NuGetPackage/$(Project.Assembly.Name).$(Build.BuildNumber).nupkg -s "$(My.GuidEndpoint)" --api-key "AzureDevopsServer"
    displayName: 'Dotnet NuGet Push to Azure Artifacts'
```
