### ISSUE TITLE
`dotnet.exe nuget push` command now supports -skipDuplicate like nuget.exe did.

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8100]
## Details about Problem
Related Issue: https://github.com/NuGet/Home/issues/1630

In the related issue, NuGet.exe push was given a new option, -SkipDuplicate. This option needs to be made available in DotNet.exe nuget push as --skip-duplicate.

NuGet product used: dotnet.exe

**Comment by adamralph** [comment]
Really? We've waited so long (3.5 years) for https://github.com/NuGet/Home/issues/1630 to be released, now we have to wait again for `dotnet` to support it?

**Comment by adamralph** [comment]
To clarify my expectation: https://github.com/NuGet/Home/issues/1630 should have included the required changes to `dotnet`. Without that, the feature is of little use. No one really wants to go back to bootstrapping nuget.exe in build scripts. The expectation is to use always use `dotnet`.

**Comment by adamralph** [comment]
In which version of the .NET SDK can we expect this change?

**Comment by rrelyea** [comment]
It has missed NuGet 5.3 release. We hope to get it in 5.4, but it is currently behind some other priorities. 5.4 would likely mean 3.0.200 would have it. (to clarify...some test infrastructure investigation and test work is what still remains for the dotnet.exe side of this work -- coding is the easy part - making sure it is well tested is more challenging)

**Comment by donnie-msft** [comment]
> In which version of the .NET SDK can we expect this change?

@adamralph - should be in NET Core 3.1 SDK

**Comment by diegosasw** [comment]
I've just tried the --skip-duplicate successfully with azure pipelines and dotnet core 3.1 preview
```
- task: NuGetAuthenticate@0
  displayName: 'Authenticate in NuGet feed'
- task: UseDotNet@2
  displayName: 'Use latest .NET Core sdk 3.x'
  inputs:
    packageType: sdk
    version: 3.x
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: dotnet nuget push $(PATH_PIPELINE_ARTIFACT_NAME)/**/*.nupkg --source $(NUGET_FEED) --api-key $(NUGET_API_KEY) --skip-duplicate
  displayName: 'Uploads nuGet packages'
```
