### ISSUE TITLE
Running dotnet nuget push on GPR randomly fails

### ISSUE THREAD

**Issue by fabich** [NuGet/Home#9493]
## Details about Problem

Error:
```
Run dotnet nuget push *.nupkg --skip-duplicate --source GPR
warn : No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/yaos'. To save an API Key for a source use the 'setApiKey' command.
Pushing yaos.OpenAPI.Diff.1.1.2-alpha.30.nupkg to 'https://nuget.pkg.github.com/yaos'...
  PUT https://nuget.pkg.github.com/yaos/
An error was encountered when fetching 'PUT https://nuget.pkg.github.com/yaos/'. The request will now be retried.
An error occurred while sending the request.
  The response ended prematurely.
  PUT https://nuget.pkg.github.com/yaos/
An error was encountered when fetching 'PUT https://nuget.pkg.github.com/yaos/'. The request will now be retried.
An error occurred while sending the request.
  The response ended prematurely.
  PUT https://nuget.pkg.github.com/yaos/
error: An error occurred while sending the request.
error:   The response ended prematurely.
```

dotnet --version 3.1.201
dotnet nuget --version 5.5.0.4
OS version: ubuntu-latest

## Detailed repro steps so we can see the same problem
Running the following action:
```
name: Publish pre-release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    name: Publish OpenAPI Diff Action tool to nuget
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup nbgv
        uses: aarnott/nbgv@v0.3
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Add GPR Source
        run: dotnet nuget add source https://nuget.pkg.github.com/yaos/index.json --name GPR --username fabich --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Publish the package
        run: dotnet nuget push *.nupkg --skip-duplicate --source GPR
        working-directory: ./src/yaos.OpenAPI.Diff/nupkg
```

## Workaround
```
- name: Publish the package
        run: |
          until dotnet nuget push *.nupkg --skip-duplicate --source GPR; do echo "Retrying"; sleep 1; done
        working-directory: ./src/yaos.OpenAPI.Diff/nupkg
```
There is a similar issue #8580 that has been closed but I don't think that the suggested workaround works.

**Comment by zkat** [comment]
Please refer to https://stackoverflow.com/questions/57889719/how-to-push-nuget-package-in-github-actions for how to configure this.

**Comment by ghost** [comment]
I have a similar issue where push to GPR seems to be randomly failing. Our authentication is defined in a nuget.config file in the root of the project repository. Our build only runs on Windows.
 
```lang=xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="github" value="https://nuget.pkg.github.com/<org>/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <github>
        <add key="Username" value="Github CI" />
        <add key="ClearTextPassword" value="%GITHUB_TOKEN%" />
      </github>
  </packageSourceCredentials>
</configuration>
```

**Comment by fabich** [comment]
@zkat I'm still running into the same issue with the solution you suggested.

`warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
  Unauthorized https://nuget.pkg.github.com/<corp>/ 451ms
error: Response status code does not indicate success: 401 (Unauthorized).`

my yml:
```
name: Publish API Clients

on:
  push:
    branches:
      - master
      - preview
      - unofficial
  watch:
    types: [started]

jobs:
  publish-csharp:
    runs-on: ubuntu-latest
    name: Publish C# Clients
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/<corp>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup nbgv
        uses: aarnott/nbgv@v0.3
      - name: Create the package
        run: dotnet pack --configuration Release --output out
        working-directory: ./src/API/csharp/<pkg>
      - name: Push generated package to GitHub registry
        run: dotnet nuget push *.nupkg --skip-duplicate --no-symbols true
        working-directory: ./src/API/csharp/<pkg>/out/
```

my .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>...</PackageId>
    <Authors>...</Authors>
    <Company>...</Company>
    <Description>Cross Platform API Client for ....</Description>
    <Copyright>...</Copyright>
    <PackageTags>...</PackageTags>
    <RepositoryUrl>...</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
  </ItemGroup>

</Project>
```

may I kindly ask you to reopen this issue?
